// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3dmTLGl5jTUf916P1HwudZHebi_HBltI',
    appId: '1:874603783237:web:2944eb2c4b0a4d41afaf2c',
    messagingSenderId: '874603783237',
    projectId: 'aptitudeapp-2489d',
    authDomain: 'aptitudeapp-2489d.firebaseapp.com',
    storageBucket: 'aptitudeapp-2489d.firebasestorage.app',
    measurementId: 'G-ZZ6QHF1SDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCibUQiytUSahYbSnfRp7PdoQPQLCSpEgg',
    appId: '1:874603783237:android:9de14714330d0f71afaf2c',
    messagingSenderId: '874603783237',
    projectId: 'aptitudeapp-2489d',
    storageBucket: 'aptitudeapp-2489d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt3NROxYdYxwNn90-_KP4s3bde3MJj63U',
    appId: '1:874603783237:ios:f0e0dc74f7ed7cf1afaf2c',
    messagingSenderId: '874603783237',
    projectId: 'aptitudeapp-2489d',
    storageBucket: 'aptitudeapp-2489d.firebasestorage.app',
    iosBundleId: 'com.example.aptitude',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt3NROxYdYxwNn90-_KP4s3bde3MJj63U',
    appId: '1:874603783237:ios:f0e0dc74f7ed7cf1afaf2c',
    messagingSenderId: '874603783237',
    projectId: 'aptitudeapp-2489d',
    storageBucket: 'aptitudeapp-2489d.firebasestorage.app',
    iosBundleId: 'com.example.aptitude',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3dmTLGl5jTUf916P1HwudZHebi_HBltI',
    appId: '1:874603783237:web:b79e24df6527d98dafaf2c',
    messagingSenderId: '874603783237',
    projectId: 'aptitudeapp-2489d',
    authDomain: 'aptitudeapp-2489d.firebaseapp.com',
    storageBucket: 'aptitudeapp-2489d.firebasestorage.app',
    measurementId: 'G-5G2X8LDP82',
  );
}
